### Create new user
POST http://localhost:8080/customers
Content-Type: application/json
Authorization: Basic manager_1 01_manager_01

{
    "full_name":"Mark Tan",
    "nric":"S8291266I",
    "phone":"91251234",
    "address":"27 Jalan Alamak S680234",
    "username":"rubbish",
    "password":"password",
    "authorities":"ROLE_USER",
    "active": true
}

### Login to user account
POST http://localhost:8080/login
Accept: application/json
Authorization: Basic bryan password

### Login to manager account
POST http://localhost:8080/login
Accept: application/json
Authorization: Basic manager_1 01_manager_01

### Open account as manager
POST http://localhost:8080/accounts
Content-Type: application/json
Authorization: Basic manager_1 01_manager_01

{
    "customer_id":4,
    "balance":"nonsense",
    "available_balance":0.0
}

### View own accounts as user
GET http://localhost:8080/accounts
Accept: application/json
Authorization: Basic rubbish password

### View each account as user
GET http://localhost:8080/accounts/71
Accept: application/json
Authorization: Basic bryan password