### Create new user
POST http://localhost:8081/customers
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYW5hZ2VyXzEiLCJ1aWQiOjEsImF1dGgiOiJST0xFX01BTkFHRVIiLCJleHAiOjE2MDE5OTgzNDZ9.IoJywDJUqXx7dLoe1IxeuGWz-RQyG1TG_D_Sx1nPqO6xWxB8lwrr1vDO9JpbSI-HHTz6Sx3UdqD7ZqsyKZBkYw

{
    "full_name":"Mark Tan",
    "nric":"S8291266I",
    "phone":"91251234",
    "address":"27 Jalan Alamak S680234",
    "username":"bryan",
    "password":"password",
    "authorities":"ROLE_USER",
    "active": true
}

### Get JWT for user
POST http://localhost:8081/login
Accept: application/json
Authorization: Basic bryan password

### Get JWT for manager
POST http://localhost:8081/login
Accept: application/json
Authorization: Basic manager_1 01_manager_01

### Create account as manager
#For testing, decode the JWT and replace the "customer_id" field with the decoded uid
POST http://localhost:8083/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYW5hZ2VyXzEiLCJ1aWQiOjEsImF1dGgiOiJST0xFX01BTkFHRVIiLCJleHAiOjE2MDIyMzAyNDV9.2RnXwD68UFPUlekC3sM4H-UrSUnm3a97yqqmK6E6DN_3nxuBnHw3BDwlDYECXbeDllLY89gg_vliB1mtPl05pQ

{
    "customer_id":4,
    "balance":0.0,
    "available_balance":0.0
}

### View own accounts as user
GET http://localhost:8083/
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJicnlhbiIsInVpZCI6NCwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTYwMjIzMTA5OX0.o5Ob4w7Fuufz7KRE1PBIkN_U7G_wDYquC9zq-XqZoe769BaqL-WyeL1NN_ip4p_RpEKY53NyF1GIa4kdq21eGQ
### View each account as user
GET http://localhost:8083/51
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJicnlhbiIsInVpZCI6NCwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTYwMjIzMTA5OX0.o5Ob4w7Fuufz7KRE1PBIkN_U7G_wDYquC9zq-XqZoe769BaqL-WyeL1NN_ip4p_RpEKY53NyF1GIa4kdq21eGQ